data: !include data/openwebtext_source.yaml
model:
  type: aether
  model_dim: 768
  ff_dim: 2048
  query_count: 16
  kv_count: 4
  layer_count: 12
  norm_eps: 1e-6
  seq_len: 1024
  vocab_size: 32000
  gradient_checkpointing: true
trainer:
  wandb:
    project: "aether"
    tags: [ "openwebtext", "gpt2", "itest"]

  mp: p=bfloat16,c=bfloat16
  model_axis_size: 1
  per_device_parallelism: 8

  train_batch_size: 512
  num_train_steps: 20000
optimizer:
  learning_rate: 1e-3
  weight_decay: 0.1
  warmup: 0.01
  beta1: 0.9
  beta2: 0.95
  epsilon: 1e-5
  max_grad_norm: 1.0